
// export const AUTHENTICATE_USER_INIT = 'AUTHENTICATE_USER_INIT'
// export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
// export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE'